config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  get 'about' => 'home#about'
  get 'portfolio' => 'home#portfolio'
  get 'feed' => 'articles#feed', :format => 'rss'
  resources :articles

  get 'login' => 'home#login'

end

app/models/article.rb
class Article < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged
  belongs_to :user
  
  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize.to_s
  end
  def slug_candidates
    [
      :title,
      [:title, :id]
    ]
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :role
  has_many :articles
  before_create :set_default_role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  private
  def set_default_role
    self.role ||= Role.find_by_name('default')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :feed]
  before_action :check_permission, except: [:show, :feed]
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
  end

  # GET /articles/new
  def new
    @article = Article.new
    #authorize @article
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def feed
    @articles = Article.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :text)
    end

    def check_permission
      redirect_to root_path if current_user.role != Role.find_by_name("admin")
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @articles = Article.all.order(created_at: :desc)
  end

  def login
    redirect_to new_user_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def getCustomStrftime(time)
    return time.strftime('%A, %d %B, %Y')
  end
  def content_title(subtitle)
    content_for :title, subtitle + " - George Web Labs"
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  class HTMLWithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      sha = Digest::SHA1.hexdigest(code)
      Rails.cache.fetch ["code", language, sha].join('-') do
        Pygments.highlight(code, lexer: language)
      end
    end
  end

  def markdown(text)
    #renderer = Redcarpet::Render::HTML.new(hard_wrap: true,safe_links_only: true, filter_html: false)
    renderer = HTMLWithPygments.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      tables: true,
      space_after_headers: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end

app/views/articles/_form.html.erb
  <%= form_for(@article) do |f| %>
    <% if @article.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

        <ul>
        <% @article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :text %>
      <%= f.text_area :text, rows: 15, class: "form-control" %></p>
    </div>
    <%= f.submit 'submit', class: "btn btn-default" %>
  <% end %>

app/views/articles/edit.html.erb
<div class="container">
  <h1>Editing article</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @article %> |
  <%= link_to 'Back', articles_path %>
</div>

app/views/articles/index.html.erb
<div class="container">
<h1>Listing articles</h1>
<%= link_to 'New Article', new_article_path %>
<table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= getCustomStrftime(article.created_at) %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/articles/new.html.erb
<div class="container">
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<%= content_title(@article.title) %>
<div class="container">
  <div class="row">
    <% if user_signed_in? %>
      <%= link_to 'Edit', edit_article_path(@article) %> |
      <%= link_to 'Back', root_path %>
    <% end %>
  </div>
  <p id="notice"><%= notice %></p>
  <div class="row article-title">
    <h1><%= @article.title %></h1>
  </div>
  <div class="row article-text">
    <div class="col-md-8 col-md-offset-2">
      <%= markdown @article.text %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div id="disqus_thread"></div>
    </div>
  </div>
</div>

<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'georgewelabs'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/common/_footer.html.erb
<footer>
  <div class="row">
    <div class="col-md-12 centered-text">
    <p>&copy; <%= Time.now.year %> George Web Labs</p>
    </div>
  </div>
</footer>

app/views/common/_nav.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">George Web Labs</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'BLOG', root_path %></li>
        <li><%= link_to 'ABOUT', about_path %></li>
        <li><%= link_to 'PORTFOLIO', portfolio_path %></li>
        <% if user_signed_in? %>
          <p class="navbar-text">Signed in as <%= current_user.name %></p>
          <li><%= link_to 'Articles', articles_path if current_user.role == Role.find_by_name("admin") %></li>
          <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/home/about.html.erb
<div class="container">
<h1 class="centered-text">About Me</h1>
  <div class="row">
    <div class="col-xs-12">
      <img class="img-circle img-centerable avatar-img" src="https://c1.staticflickr.com/9/8708/17446570459_5f95600368_m.jpg" style="max-width: 100%;" alt="avatar">
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <p>Hi, I am George, a programmer who dreams and pursues excellence. I work in a small company as a Technical lead. Welcome to my blog!</p>
      <ul class="social-network">
        <li><a class="social-icon" href="https://github.com/georgeweblabs" target="_blank"><i class="fa fa-github"></i></a></li>
        <li><a class="social-icon" href="https://tw.linkedin.com/in/georgechang0117" target="_blank"><i class="fa fa-linkedin"></i></a></li>
        <li><a class="social-icon" href="https://www.instagram.com/georgechang.ig" target="_blank"><i class="fa fa-instagram"></i></a></li>
        <li><a class="social-icon" data-container="body" data-toggle="popover" data-placement="top" data-content="georgechang0117(at)gmail(dot)com"><i class="fa fa-envelope"></i></a></li>
      </ul>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="main">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
      <% @articles.each do |article| %>
        <div class="post">
          <div class="post-title">
            <%= link_to article.title, article_path(article) %>
          </div>
          <div class="post-info">
            <p><%= getCustomStrftime(article.created_at) %></p>
          </div>
          <div class="post-text">
            
          </div>
        </div>
      <% end %>
      </div>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="row">
              <div class="center-block">
                <h3 class="centered-text">About George</h3>
                <a href="<%= about_path %>"><img class="img-circle img-centerable avatar-img" src="https://c1.staticflickr.com/9/8708/17446570459_5f95600368_m.jpg" width="200" height="200" alt="avatar"></a>
                <p class="blocktext">I am a programmer who dreams and pursues excellence.</p>
                <ul class="social-network">
                  <li><a class="social-icon" href="https://github.com/georgeweblabs" target="_blank"><i class="fa fa-github"></i></a></li>
                  <li><a class="social-icon" href="https://tw.linkedin.com/in/georgechang0117" target="_blank"><i class="fa fa-linkedin"></i></a></li>
                  <li><a class="social-icon" href="https://www.instagram.com/georgechang.ig" target="_blank"><i class="fa fa-instagram"></i></a></li>
                  <li><a class="social-icon" data-container="body" data-toggle="popover" data-placement="top" data-content="georgechang0117(at)gmail(dot)com"><i class="fa fa-envelope"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/home/portfolio.html.erb
<div class="container">
<h1 class="">Portfolio</h1>
  <div class="row">
    <div class="col-xs-12">
      <h3><a href="#kutures" class="anchor"><i class="fa fa-anchor"></i></a>Kutures <small>a powerful futures application</small></h3>

      <figure>
        <%= image_tag "http://i.imgur.com/0L5p4hp.png", class: "img-responsive", alt: "Product list" %>
        <figcaption>Product list (Auto Refresh)</figcaption>
      </figure>
      <figure>
        <%= image_tag "http://i.imgur.com/UtKDN6k.png", class: "img-responsive", alt: "Trend chart & Product info" %>
        <figcaption>Trend chart & Product info</figcaption>
      </figure>
      <figure>
        <%= image_tag "http://i.imgur.com/DOAGaRc.png", class: "img-responsive", alt: "Trend with cross line" %>
        <figcaption>Trend with cross line</figcaption>
      </figure>
      <figure>
        <%= image_tag "http://i.imgur.com/HiZrBTS.png", class: "img-responsive", alt: "Candle stick chart" %>
        <figcaption>Candle stick chart</figcaption>
      </figure>
      <figure>
        <%= image_tag "http://i.imgur.com/7CAwFLT.png", class: "img-responsive", alt: "Candle stick chart with cross line" %>
        <figcaption>Candle stick chart with cross line</figcaption>
      </figure>
      <figure>
        <%= image_tag "http://i.imgur.com/kh8Zzct.png", class: "img-responsive", alt: "Order details" %>
        <figcaption>Order details</figcaption>
      </figure>
      <figure>
        <%= image_tag "http://i.imgur.com/UMn6eKP.png", class: "img-responsive", alt: "Daily report" %>
        <figcaption>Daily report</figcaption>
      </figure>
      <figure>
        <%= image_tag "http://i.imgur.com/FAokg04.png", class: "img-responsive", alt: "Order control pad" %>
        <figcaption>Order control pad</figcaption>
      </figure>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "George Web Labs" %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'common/nav' %>
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
    <%= render 'common/footer' %>
    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-60680880-1', 'auto');
    ga('send', 'pageview');
    </script>
  </body>
</html>